blank_issues_enabled: true
contact_links:
  - name: Checkout the wiki
    url: https://mcpelauncher.readthedocs.io
    about: You find useful information about this launcher
  - name: Ask on Discord
    url: https://discord.gg/TaUNBXr
    about: You can ask for help here!
